# Log config
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_RUNTIME_FILTERING=y
CONFIG_LOG_BUFFER_SIZE=2048
CONFIG_LOG_PRINTK=y
CONFIG_LOG_PROCESS_TRIGGER_THRESHOLD=0
CONFIG_COVERAGE=n
CONFIG_LOG_TAG_MAX_LEN=8

# RTT config
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_LOG_BACKEND_RTT=y

# Thread config
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_NAME=y

# Debugging
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_APP_LOG_LEVEL_DBG=y
CONFIG_CHANNEL_LOG_LEVEL_DBG=y

# Storage configuration
CONFIG_NVS=y
